version: "3.2"
services:
  postgres:
    image: "crunchydata/crunchy-postgres:centos8-13.6-4.7.5"
    env_file:
    - ".env"
    environment:
    - "MODE=postgres"
    - "PG_DATABASE=postgres"
    - "PG_PRIMARY_PORT=5432"
    - "PG_MODE=primary"
    - "PG_USER=postgres"
    - "PG_PASSWORD=${DEV_DB_PASSWORD}"
    - "PG_PRIMARY_USER=primary"
    - "PG_PRIMARY_PASSWORD=${DEV_DB_PRIMARY_PASSWORD}"
    - "PG_ROOT_PASSWORD=${DEV_DB_ROOT_PASSWORD}"
    - "PGDATA_PATH_OVERRIDE=postgres"
    volumes:
    - "postgres:/pgdata"
    ports:
    - "5433:5432"
    networks:
    - crunchynet
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == worker

  mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: 'Mail'
        logging:
            driver: 'none'  # disable saving logs
        environment:
            MH_AUTH_FILE: /mailhog.auth
            MH_MAILDIR_PATH: /data
            MH_STORAGE: maildir
        volumes:
            - ./mailhog.auth:/mailhog.auth:ro
            - ./data:/data:rw
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - crunchynet


networks:
  crunchynet:

volumes:
  postgres:
